Feat(API): implementação de Controllers
puzzlsoftwarehouse/event_manager pull request #4
Opened 2022-02-07 23:58 UTC by silviamichele

2022-02-08 01:35 UTC, vitumenezes requested changes
Comentário geral: usa mais as tipagens pra te ajudar. tanto nos parâmetros quanto nos retornos das funções, o autocomplete é o teu melhor amigo e te salva demais!!

2022-02-08 01:35 UTC, vitumenezes commented on app/controllers/event/event_controller.py
> +            self.session.query(Event).filter(Event.id == event_id)
aqui deveria ter uma ação de `delete`?

2022-02-08 01:35 UTC, vitumenezes commented on app/controllers/status/status_controller.py
> +        if name and len(name) > 3:
caso isso seja falso, adicionar um **Status** sem um **name** é correto? se sim, safe do safe :D

se não, é legal criar uma validação :D

2022-02-08 01:35 UTC, vitumenezes commented on app/controllers/user/user_controllers.py
> +            user.name = name
dá um respiro aqui com uma ou outra linha em branco, separando um pouco os "blocos" que fazem certas "tarefas", saca?

2022-02-08 10:36 UTC, silviamichele commented on app/controllers/event/event_controller.py
> +            self.session.query(Event).filter(Event.id == event_id)
era ;/

2022-02-08 10:41 UTC, silviamichele commented on app/controllers/user/user_controllers.py
> +            user.name = name
simm, inclui validação tbm

2022-02-08 14:00 UTC, Hellyson-Ferreira requested changes

2022-02-09 19:51 UTC, Hellyson-Ferreira approved these changes

2022-02-09 19:53 UTC, merged